### ISSUE TITLE
`ecs wait-for-deployment` fails with error

### ISSUE THREAD

**Issue by lasuillard** [lasuillard/aws-annoying#50]
Console output:

```plaintext
ℹ️ Looking up running deployment for service <REDACTED>
⚠️ `wait_for_start` is set, will wait for a new deployment to start.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /opt/pipx/venvs/aws-annoying/lib/python3.12/site-packages/aws_annoying/cli/e │
│ cs/wait_for_deployment.py:69 in wait_for_deployment                          │
│                                                                              │
│   66 │   waiter = ECSDeploymentWaiter(ECSServiceRef(cluster=cluster, service │
│   67 │   try:                                                                │
│   68 │   │   with Timeout(timeout_seconds):                                  │
│ ❱ 69 │   │   │   waiter.wait(                                                │
│   70 │   │   │   │   wait_for_start=wait_for_start,                          │
│   71 │   │   │   │   polling_interval=polling_interval,                      │
│   72 │   │   │   │   wait_for_stability=wait_for_stability,                  │
│                                                                              │
│ /opt/pipx/venvs/aws-annoying/lib/python3.12/site-packages/pydantic/_internal │
│ /_validate_call.py:39 in wrapper_function                                    │
│                                                                              │
│    36 │   │                                                                  │
│    37 │   │   @functools.wraps(wrapped)                                      │
│    38 │   │   def wrapper_function(*args, **kwargs):                         │
│ ❱  39 │   │   │   return wrapper(*args, **kwargs)                            │
│    40 │                                                                      │
│    41 │   # We need to manually update this because `partial` object has no  │
│    42 │   wrapper_function.__name__ = extract_function_name(wrapped)         │
│                                                                              │
│ /opt/pipx/venvs/aws-annoying/lib/python3.12/site-packages/pydantic/_internal │
│ /_validate_call.py:136 in __call__                                           │
│                                                                              │
│   133 │   │   if not self.__pydantic_complete__:                             │
│   134 │   │   │   self._create_validators()                                  │
│   135 │   │                                                                  │
│ ❱ 136 │   │   res = self.__pydantic_validator__.validate_python(pydantic_cor │
│   137 │   │   if self.__return_pydantic_validator__:                         │
│   138 │   │   │   return self.__return_pydantic_validator__(res)             │
│   139 │   │   else:                                                          │
│                                                                              │
│ /opt/pipx/venvs/aws-annoying/lib/python3.12/site-packages/aws_annoying/ecs/d │
│ eployment_waiter.py:56 in wait                                               │
│                                                                              │
│    53 │   │   │   "Looking up running deployment for service %s",            │
│    54 │   │   │   self.service_ref.service,                                  │
│    55 │   │   )                                                              │
│ ❱  56 │   │   latest_deployment_arn = self.get_latest_deployment_arn(        │
│    57 │   │   │   wait_for_start=wait_for_start,                             │
│    58 │   │   │   polling_interval=polling_interval,                         │
│    59 │   │   )                                                              │
│                                                                              │
│ /opt/pipx/venvs/aws-annoying/lib/python3.12/site-packages/pydantic/_internal │
│ /_validate_call.py:39 in wrapper_function                                    │
│                                                                              │
│    36 │   │                                                                  │
│    37 │   │   @functools.wraps(wrapped)                                      │
│    38 │   │   def wrapper_function(*args, **kwargs):                         │
│ ❱  39 │   │   │   return wrapper(*args, **kwargs)                            │
│    40 │                                                                      │
│    41 │   # We need to manually update this because `partial` object has no  │
│    42 │   wrapper_function.__name__ = extract_function_name(wrapped)         │
│                                                                              │
│ /opt/pipx/venvs/aws-annoying/lib/python3.12/site-packages/pydantic/_internal │
│ /_validate_call.py:136 in __call__                                           │
│                                                                              │
│   133 │   │   if not self.__pydantic_complete__:                             │
│   134 │   │   │   self._create_validators()                                  │
│   135 │   │                                                                  │
│ ❱ 136 │   │   res = self.__pydantic_validator__.validate_python(pydantic_cor │
│   137 │   │   if self.__return_pydantic_validator__:                         │
│   138 │   │   │   return self.__return_pydantic_validator__(res)             │
│   139 │   │   else:                                                          │
│                                                                              │
│ /opt/pipx/venvs/aws-annoying/lib/python3.12/site-packages/aws_annoying/ecs/d │
│ eployment_waiter.py:156 in get_latest_deployment_arn                         │
│                                                                              │
│   153 │   │   │   msg = "No running deployments found for service."          │
│   154 │   │   │   raise NoRunningDeploymentError(msg)                        │
│   155 │   │                                                                  │
│ ❱ 156 │   │   latest_deployment = sorted(running_deployments, key=itemgetter │
│   157 │   │   if len(running_deployments) > 1:                               │
│   158 │   │   │   logger.warning(                                            │
│   159 │   │   │   │   "%d running deployments found for service. Using most  │
╰──────────────────────────────────────────────────────────────────────────────╯
KeyError: 'startedAt'
Error: Process completed with exit code 1.
```

CI workflow content (GitHub Actions, partial):

```yaml
      - name: Deploy to ECS service
        id: deploy-ecs
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-definition.outputs.task-definition }}
          cluster: ${{ vars.AWS_ECS_CLUSTER }}
          service: ${{ vars.AWS_ECS_SERVICE }}
          wait-for-service-stability: false

      - name: Wait for deployment complete
        run: |
          pipx install 'aws-annoying~=0.6.0'
          aws-annoying ecs wait-for-deployment \
            --cluster '${{ vars.AWS_ECS_CLUSTER }}' \
            --service '${{ vars.AWS_ECS_SERVICE }}' \
            --wait-for-start \
            --wait-for-stability \
            --timeout-seconds 600 \
            --expected-task-definition '${{ steps.deploy-ecs.outputs.task-definition-arn }}'
```
